CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE passwd (
    id INT PRIMARY KEY REFERENCES users(id),
    passwd VARCHAR(255) NOT NULL
);

CREATE TABLE courses (
    course_name VARCHAR(255) UNIQUE NOT NULL,
    available_spots INT NOT NULL
);

ALTER TABLE users
ADD COLUMN uuid UUID UNIQUE NOT NULL;

ALTER TABLE users
ADD COLUMN isVerified BOOLEAN DEFAULT FALSE;

ALTER TABLE users
ADD COLUMN verificationCode VARCHAR(255);

ALTER TABLE users
ADD COLUMN tokens INT CHECK (tokens <= 5) DEFAULT 0;

ALTER TABLE users
ADD COLUMN name VARCHAR(255);
